name: Release
on:
  push:
    tags:
      - '*'
jobs:
  call-release-reusable:
    uses:
      devopsb78/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-backend
      release_archive_file: "*.js package.json schema VERSION"
      npm_install: true
    secrets: inherit
